### ISSUE TITLE
RSS feed for article zip files

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-download#4]
How do people discover or are notified when a new article zip file is added to the bucket? The prevailing solution is to use RSS. 

It could be a new feed, or the article zip file URL could be added to an existing feed. 

Is this something ``observer`` would do? 

Would we want a separate RSS feed for PoA and VoR articles?

I can describe the overall picture or discuss as needed, hoping for some comments from @lsh-0.

**Comment by gnott** [comment]
In the case an article is part of a silent correction, the RSS feed would not need to be updated.

**Comment by lsh-0** [comment]
hey @gnott 

> when a new article zip file is added to the bucket

just so it's clear to me, we're talking about the zip file that contains the final article pdf, xml file and all it's attached media, right?

and is being notified when an article zip file changes any different to being notified when a new version of an article is published? if not, then who/what is monitoring for changes in these files?

S3 buckets can be configured to emit events when their contents change. It wouldn't take much to have an internal service collect these events and serve them as a feed. `observer` could do it, although I'd prefer it not being the primary source of the data, just an aggregator, as it's meant for reporting, and reporting data is often denormalised to make things more efficient. If these events could be pulled from CloudTrail or logged to another bucket that would be better.

Including @giorgiosironi for his thoughts.

**Comment by lsh-0** [comment]
also, no jira love?

**Comment by lsh-0** [comment]
jira: https://elifesciences.atlassian.net/browse/ELPP-3658
